### ISSUE TITLE
Request for mathematical operator support when mapping 'fields as'

### ISSUE THREAD

**Issue by martin-kieliszek** [manu-de-verdun/sql-json-generator#9]
Is it possible to enable "$fields" object to specify a custom mathematical operation to be run over the column before being marked "as" a new column?

For example:
```
select stats.mac_addr
, stats.service_octets_passed / 1024 as KB_IN_HOUR
, (stats.service_octets_passed / 1024) / 1024 as MB_IN_HOUR
, ((stats.service_octets_passed / 1024) / 1024) /1024 as GB_IN_HOUR
, stats.service_class_name
from tableA stats
where stats.mac_addr='AA-BB-CC-DD-EE-FF';
``` 

In the above instance, three separate columns have different custom mathematical operations run over them. I understand that you currently make available a $function key such as:
```
$function : 'acos'
```
However I'd like to essentially be able to do

```
$customFunc: '(($field / 1024) / 1024) /1024)'
```

Would like to get your opinion and thoughts. Would also like to thank you again for such a great library.

**Comment by manu-de-verdun** [comment]
Hi !

Well.... you're right, for simple function you can use `$function : 'acos'`, but there is no way to inject field into a custom function.

I think that it's a great feature to create, a kind of 

```
{ $inject : {
    $customFunction: '(( $arg / 1024) / 1024) /1024)',
    $args: [{ $field: 'service_octets_passed'}],
    $as : 'KB_IN_HOUR'
}}
```

where it will be possible to inject more than one field...


_but unfortunately, I do not have time to do it right now...._

here is a workaround to built your sql statment. not really clean, but that's why I've created the $raw, as a workaround for unexpected SQL statments 

```
{
    $from: 'tableA',
    $fields: [
        {$raw: 'tableA.service_octets_passed / 1024 as KB_IN_HOUR'},
        {$raw: '(tableA.service_octets_passed / 1024) / 1024 as MB_IN_HOUR'},
        {$raw: '((tableA.service_octets_passed / 1024) / 1024) /1024 as GB_IN_HOUR'},
        ,'service_class_name'
    ],
    $where: [{mac_addr: 'AA-BB-CC-DD-EE-FF'}]
}
```

**Comment by martin-kieliszek** [comment]
Closing this issue as you have provided $raw capability

Thanks again,
Marty!
